### ISSUE TITLE
Examples of study definition mistakes whose exception lack context

### ISSUE THREAD

**Issue by inglesp** [opensafely/cohort-extractor#554]
Here are some examples of mistakes in study definitions where an exception is raised, and where the exception does not indicate which covariate in the study definition contains the the mistake.

* `patients.with_these_clinical_events(codelist(["H3300"], "snomedct"))`
  * `ValueError: invalid literal for int() with base 10: 'H3300'`
* `patients.with_these_clinical_events(codelist(["H3300"], "ctv3"))`
  * `AssertionError` (EMIS only)
* `patients.with_these_clinical_events(..., returning="wibble")`
  * `ValueError: No matching type for 'wibble'`
* `patients.with_these_clinical_events(..., on_or_before="wibble")`
  * `cohortextractor.date_expressions.InvalidExpressionError: Unknown date name 'wibble' (allowed are index_date, today) in: wibble`

Here's an example of a full traceback:

```
Exception at 2021-05-10 15:40:41 UTC
Traceback (most recent call last):
  File "/home/inglesp/work/ebmdatalab/opensafely/cohort-extractor/cohortextractor/date_expressions.py", line 169, in get_method
    return getattr(self, f"{prefix}{name}")
AttributeError: 'DateExpressionEvaluator' object has no attribute 'date_name_wibble'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inglesp/.pyenv/versions/opensce/bin/cohortextractor", line 33, in <module>
    sys.exit(load_entry_point('opensafely-cohort-extractor', 'console_scripts', 'cohortextractor')())
  File "/home/inglesp/work/ebmdatalab/opensafely/cohort-extractor/cohortextractor/cohortextractor.py", line 779, in main
    dump_cohort_sql(options.study_definition)
  File "/home/inglesp/work/ebmdatalab/opensafely/cohort-extractor/cohortextractor/cohortextractor.py", line 506, in dump_cohort_sql
    study = load_study_definition(study_definition)
  File "/home/inglesp/work/ebmdatalab/opensafely/cohort-extractor/cohortextractor/cohortextractor.py", line 519, in load_study_definition
    return getattr(importlib.import_module(name), value)
  File "/home/inglesp/.pyenv/versions/3.7.8/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/inglesp/work/ebmdatalab/opensafely/research/Factors-associated-with-COVID-19-vaccination/analysis/study_definition_bad.py", line 6, in <module>
    codelist(["H3300"], "ctv3"), on_or_before="wibble"
  File "/home/inglesp/work/ebmdatalab/opensafely/cohort-extractor/cohortextractor/study_definition.py", line 29, in __init__
    self.set_index_date(index_date)
  File "/home/inglesp/work/ebmdatalab/opensafely/cohort-extractor/cohortextractor/study_definition.py", line 51, in set_index_date
    self._original_covariates, self.index_date
  File "/home/inglesp/work/ebmdatalab/opensafely/cohort-extractor/cohortextractor/date_expressions.py", line 28, in evaluate_date_expressions_in_covariate_definitions
    evaluate_date_expression(end),
  File "/home/inglesp/work/ebmdatalab/opensafely/cohort-extractor/cohortextractor/date_expressions.py", line 111, in __call__
    return self.parse(date_str)
  File "/home/inglesp/work/ebmdatalab/opensafely/cohort-extractor/cohortextractor/date_expressions.py", line 137, in parse
    raise e
  File "/home/inglesp/work/ebmdatalab/opensafely/cohort-extractor/cohortextractor/date_expressions.py", line 132, in parse
    return self.evaluate(**args)
  File "/home/inglesp/work/ebmdatalab/opensafely/cohort-extractor/cohortextractor/date_expressions.py", line 140, in evaluate
    date = self.get_method("name", name)()
  File "/home/inglesp/work/ebmdatalab/opensafely/cohort-extractor/cohortextractor/date_expressions.py", line 173, in get_method
    f"Unknown date {method_type} '{name}' "
cohortextractor.date_expressions.InvalidExpressionError: Unknown date name 'wibble' (allowed are index_date, today) in: wibble
```

**Comment by HelenCEBM** [comment]
Attempting to run cohort extractor with too large a population size generates no dummy data locally but without a helpful error message
![image](https://user-images.githubusercontent.com/24392156/120988256-4dc8b680-c776-11eb-89b7-e2c8fe518698.png)

**Comment by evansd** [comment]
@HelenCEBM Ah, I think this is actually a slightly separate issue which can't be addressed inside cohortextractor directly as it's to do with running out of memory. But there's a ticket in job-runner tracking this: https://github.com/opensafely-core/job-runner/issues/208
